ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
ls
ls!
ls :l
ls :l!
ls
ls ./Makefile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sl
ls
lll
ls
l
la
ls
la
ls
man tar > /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; man tar >> /tmp/bigfile; cat < /tmp/bigfile | wc; rm -f /tmp/bigfile
ls
sls
ls
ll
ls
lq
ls
