/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ast.c                                              :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: gpouyat <gpouyat@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/06/19 09:47:39 by gpouyat           #+#    #+#             */
/*   Updated: 2017/10/07 20:04:29 by gpouyat          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <ast/ast.h>

/*
** @brief Creates the Abstract Syntax Tree (AST) from the expanded user input.\n
** This function will check the `expands` t_array from the expand isn't NULL.\n
** If it is, The return value will be `E_RET_AST_ERROR`. Else,
** this function calls the ast_built function which will build the ast based
** on the user input and tokens generated by the lexer.\n
** Upon success, This function will print in the logger at a level `1` the
** phrase `The AST was successfully created`\n
** @param ast This is a pointer to the ast var that is created in another scope.
** @param expands This contains the expanded input from the `expand` module
**
** @return Returns a `t_return` value, as the `ast` is a pointer.\n
** If this function is successful, it will return `E_RET_AST_OK`.\n
** If the `expands` variable was null the return value is `E_RET_AST_ERROR`.\n
** Else, the return results are unknown.
*/

t_return		ast_create(t_btree **ast, t_array *expands)
{
	t_lim		lim;

	if (!expands)
		return (E_RET_AST_ERROR);
	lim.cnt = expands->used;
	lim.lim = -1;
	ast_built(ast, expands, lim, 1);
	log_dbg1("The AST was successfully created");
	return (E_RET_AST_OK);
}
